//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoDevelop.D.Building.CompilerPresets {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class ConfigPresets {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ConfigPresets() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonoDevelop.D.Building.CompilerPresets.ConfigPresets", typeof(ConfigPresets).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
		///&lt;Compiler&gt;
		///	&lt;VersionId&gt;DigitalMars&lt;/VersionId&gt;
		///	&lt;CompilerCommand&gt;dmd&lt;/CompilerCommand&gt;
		///	
		///	&lt;Patterns&gt;
		///		&lt;obj&gt;&quot;{0}&quot;&lt;/obj&gt;
		///		&lt;include&gt;-I&quot;{0}&quot;&lt;/include&gt;
		///		&lt;version&gt;-version&lt;/version&gt;
		///		&lt;debug&gt;-debug&lt;/debug&gt;
		///		&lt;unittest&gt;-unittest&lt;/unittest&gt;
		///		&lt;ddFlag&gt;-D&lt;/ddFlag&gt;
		///		&lt;ddMacroDefinition&gt;&quot;{0}&quot;&lt;/ddMacroDefinition&gt;
		///		&lt;ddDir&gt;&quot;-Dd{0}&quot;&lt;/ddDir&gt;
		///	&lt;/Patterns&gt;
		///
		///	&lt;TargetConfiguration Target=&quot;Executable&quot;&gt;
		///		&lt;LinkerCommand&gt;dmd&lt;/LinkerCommand&gt;
		///		&lt;DebugArgs&gt;
		///			&lt;CompilerArg [rest of string was truncated]&quot;;.
		/// </summary>
		public static string dmd {
			get {
				return ResourceManager.GetString("dmd", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
		///&lt;Compiler&gt;
		///	&lt;!-- https://bitbucket.org/goshawk/gdc/wiki/UserDocumentation --&gt;
		///	&lt;VersionId&gt;GNU&lt;/VersionId&gt;
		///	&lt;CompilerCommand&gt;gdc&lt;/CompilerCommand&gt;
		///	&lt;gdcLibPrefixing&gt;true&lt;/gdcLibPrefixing&gt;
		///	
		///	&lt;Patterns&gt;
		///		&lt;obj&gt;&quot;{0}&quot;&lt;/obj&gt;
		///		&lt;include&gt;-I&quot;{0}&quot;&lt;/include&gt;
		///		&lt;version&gt;-fversion&lt;/version&gt;
		///		&lt;debug&gt;-fdebug&lt;/debug&gt;
		///		&lt;unittest&gt;-funittest&lt;/unittest&gt;
		///		&lt;ddFlag&gt;&lt;/ddFlag&gt;
		///		&lt;ddMacroDefinition&gt;&quot;-fdoc-inc={0}&quot;&lt;/ddMacroDefinition&gt;
		///		&lt;ddDir&gt;&quot;-fdoc-dir={0}&quot;&lt;/ddDir&gt;
		///	&lt;/Patte [rest of string was truncated]&quot;;.
		/// </summary>
		public static string gdc {
			get {
				return ResourceManager.GetString("gdc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
		///&lt;Compiler&gt;
		///	&lt;!-- https://github.com/ldc-developers/ldc/blob/master/driver/cl_options.cpp --&gt;
		///	&lt;VersionId&gt;LDC&lt;/VersionId&gt;
		///	&lt;CompilerCommand&gt;ldc2&lt;/CompilerCommand&gt;
		///	&lt;gdcLibPrefixing&gt;true&lt;/gdcLibPrefixing&gt;
		///	
		///	&lt;Patterns&gt;
		///		&lt;obj&gt;&quot;{0}&quot;&lt;/obj&gt;
		///		&lt;include&gt;-I&quot;{0}&quot;&lt;/include&gt;
		///		&lt;version&gt;-d-version&lt;/version&gt;
		///		&lt;debug&gt;-d-debug&lt;/debug&gt;
		///		&lt;unittest&gt;-unittest&lt;/unittest&gt;
		///		&lt;ddFlag&gt;-D&lt;/ddFlag&gt;
		///		&lt;ddMacroDefinition&gt;&quot;{0}&quot;&lt;/ddMacroDefinition&gt;
		///		&lt;ddDir&gt;&quot;-Dd{0}&quot;&lt;/ddDir&gt;
		///	&lt;/Pat [rest of string was truncated]&quot;;.
		/// </summary>
		public static string ldc2 {
			get {
				return ResourceManager.GetString("ldc2", resourceCulture);
			}
		}
	}
}
