
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.D
{
	public partial class ResourcesCompilerOptionsPanel
	{
		private global::Gtk.Table table1;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.Entry text_BuildArgs;
		private global::Gtk.Entry text_CompilerExecutable;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.D.ResourcesCompilerOptionsPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.D.ResourcesCompilerOptionsPanel";
			// Container child MonoDevelop.D.ResourcesCompilerOptionsPanel.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(4));
			this.table1.ColumnSpacing = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = MonoDevelop.Core.GettextCatalog.GetString ("Compiler Executable");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = MonoDevelop.Core.GettextCatalog.GetString ("Build Arguments");
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.text_BuildArgs = new global::Gtk.Entry ();
			this.text_BuildArgs.CanFocus = true;
			this.text_BuildArgs.Name = "text_BuildArgs";
			this.text_BuildArgs.IsEditable = true;
			this.text_BuildArgs.InvisibleChar = '●';
			this.table1.Add (this.text_BuildArgs);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.text_BuildArgs]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.text_CompilerExecutable = new global::Gtk.Entry ();
			this.text_CompilerExecutable.CanFocus = true;
			this.text_CompilerExecutable.Name = "text_CompilerExecutable";
			this.text_CompilerExecutable.IsEditable = true;
			this.text_CompilerExecutable.MaxLength = 250;
			this.text_CompilerExecutable.InvisibleChar = '●';
			this.table1.Add (this.text_CompilerExecutable);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.text_CompilerExecutable]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
