
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.D.OptionPanels
{
	public partial class CompilerOptions
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.Notebook OptionsNotebook;
		private global::Gtk.Label label8;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.D.OptionPanels.CompilerOptions
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.D.OptionPanels.CompilerOptions";
			// Container child MonoDevelop.D.OptionPanels.CompilerOptions.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.OptionsNotebook = new global::Gtk.Notebook ();
			this.OptionsNotebook.CanFocus = true;
			this.OptionsNotebook.Name = "OptionsNotebook";
			this.OptionsNotebook.CurrentPage = 0;
			this.OptionsNotebook.ShowBorder = false;
			// Notebook tab
			global::Gtk.Label w1 = new global::Gtk.Label ();
			w1.Visible = true;
			this.OptionsNotebook.Add (w1);
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("general");
			this.OptionsNotebook.SetTabLabel (w1, this.label8);
			this.label8.ShowAll ();
			this.hbox1.Add (this.OptionsNotebook);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.OptionsNotebook]));
			w2.Position = 0;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
