
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.D
{
	public partial class ExpressionEvaluationWidget
	{
		private global::Mono.TextEditor.TextEditor editor;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.D.ExpressionEvaluationWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.D.ExpressionEvaluationWidget";
			// Container child MonoDevelop.D.ExpressionEvaluationWidget.Gtk.Container+ContainerChild
			this.editor = new global::Mono.TextEditor.TextEditor ();
			this.editor.Events = ((global::Gdk.EventMask)(256));
			this.editor.Name = "editor";
			this.editor.TabsToSpaces = false;
			this.editor.SelectionAnchor = 0;
			this.editor.HighlightSearchPattern = false;
			this.editor.IsCaseSensitive = false;
			this.editor.IsWholeWordOnly = false;
			this.Add (this.editor);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
