
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.D.Refactoring
{
	public partial class DustMiteArgDlg
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Entry tb_CommandLine;
		
		private global::Gtk.Button bn_ResetCmd;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView tb_BuildCmd;
		
		private global::Gtk.Button bn_BuildCmdReset;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TextView tb_Log;
		
		private global::Gtk.Button bn_OpenTargetFolder;
		
		private global::Gtk.Button bn_Run;
		
		private global::Gtk.Button bn_Stop;
		
		private global::Gtk.Button bn_Close;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.D.Refactoring.DustMiteArgDlg
			this.Name = "MonoDevelop.D.Refactoring.DustMiteArgDlg";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child MonoDevelop.D.Refactoring.DustMiteArgDlg.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::MonoDevelop.Core.GettextCatalog.GetString ("<b>Command line</b>");
			this.label1.UseMarkup = true;
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.tb_CommandLine = new global::Gtk.Entry ();
			this.tb_CommandLine.CanFocus = true;
			this.tb_CommandLine.Name = "tb_CommandLine";
			this.tb_CommandLine.IsEditable = true;
			this.tb_CommandLine.InvisibleChar = '•';
			this.hbox1.Add (this.tb_CommandLine);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.tb_CommandLine]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.bn_ResetCmd = new global::Gtk.Button ();
			this.bn_ResetCmd.CanFocus = true;
			this.bn_ResetCmd.Name = "bn_ResetCmd";
			this.bn_ResetCmd.UseUnderline = true;
			this.bn_ResetCmd.Label = global::MonoDevelop.Core.GettextCatalog.GetString ("_Reset");
			this.hbox1.Add (this.bn_ResetCmd);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.bn_ResetCmd]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::MonoDevelop.Core.GettextCatalog.GetString ("<b>Build command ($buildCmd)</b>");
			this.label2.UseMarkup = true;
			this.vbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tb_BuildCmd = new global::Gtk.TextView ();
			this.tb_BuildCmd.HeightRequest = 80;
			this.tb_BuildCmd.CanFocus = true;
			this.tb_BuildCmd.Name = "tb_BuildCmd";
			this.tb_BuildCmd.AcceptsTab = false;
			this.GtkScrolledWindow.Add (this.tb_BuildCmd);
			this.hbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow]));
			w8.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.bn_BuildCmdReset = new global::Gtk.Button ();
			this.bn_BuildCmdReset.CanFocus = true;
			this.bn_BuildCmdReset.Name = "bn_BuildCmdReset";
			this.bn_BuildCmdReset.UseUnderline = true;
			this.bn_BuildCmdReset.Label = global::MonoDevelop.Core.GettextCatalog.GetString ("Reset");
			this.hbox2.Add (this.bn_BuildCmdReset);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.bn_BuildCmdReset]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::MonoDevelop.Core.GettextCatalog.GetString ("<b>Output</b>");
			this.label3.UseMarkup = true;
			this.vbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label3]));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.tb_Log = new global::Gtk.TextView ();
			this.tb_Log.CanFocus = true;
			this.tb_Log.Name = "tb_Log";
			this.tb_Log.Editable = false;
			this.tb_Log.AcceptsTab = false;
			this.GtkScrolledWindow1.Add (this.tb_Log);
			this.vbox2.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow1]));
			w13.Position = 5;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w14.Position = 0;
			// Internal child MonoDevelop.D.Refactoring.DustMiteArgDlg.ActionArea
			global::Gtk.HButtonBox w15 = this.ActionArea;
			w15.Name = "dialog1_ActionArea";
			w15.Spacing = 10;
			w15.BorderWidth = ((uint)(5));
			w15.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.bn_OpenTargetFolder = new global::Gtk.Button ();
			this.bn_OpenTargetFolder.CanFocus = true;
			this.bn_OpenTargetFolder.Name = "bn_OpenTargetFolder";
			this.bn_OpenTargetFolder.UseUnderline = true;
			this.bn_OpenTargetFolder.Label = global::MonoDevelop.Core.GettextCatalog.GetString ("_Open Target Directory");
			global::Gtk.Image w16 = new global::Gtk.Image ();
			w16.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_folder", global::Gtk.IconSize.Menu);
			this.bn_OpenTargetFolder.Image = w16;
			this.AddActionWidget (this.bn_OpenTargetFolder, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w15 [this.bn_OpenTargetFolder]));
			w17.Expand = false;
			w17.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.bn_Run = new global::Gtk.Button ();
			this.bn_Run.CanFocus = true;
			this.bn_Run.Name = "bn_Run";
			this.bn_Run.UseStock = true;
			this.bn_Run.UseUnderline = true;
			this.bn_Run.Label = "gtk-execute";
			this.AddActionWidget (this.bn_Run, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w15 [this.bn_Run]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.bn_Stop = new global::Gtk.Button ();
			this.bn_Stop.Sensitive = false;
			this.bn_Stop.CanDefault = true;
			this.bn_Stop.CanFocus = true;
			this.bn_Stop.Name = "bn_Stop";
			this.bn_Stop.UseStock = true;
			this.bn_Stop.UseUnderline = true;
			this.bn_Stop.Label = "gtk-stop";
			this.AddActionWidget (this.bn_Stop, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w15 [this.bn_Stop]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.bn_Close = new global::Gtk.Button ();
			this.bn_Close.CanDefault = true;
			this.bn_Close.CanFocus = true;
			this.bn_Close.Name = "bn_Close";
			this.bn_Close.UseStock = true;
			this.bn_Close.UseUnderline = true;
			this.bn_Close.Label = "gtk-close";
			w15.Add (this.bn_Close);
			global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w15 [this.bn_Close]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 848;
			this.DefaultHeight = 491;
			this.Show ();
			this.bn_ResetCmd.Clicked += new global::System.EventHandler (this.OnBnResetCmdClicked);
			this.bn_BuildCmdReset.Clicked += new global::System.EventHandler (this.OnBnBuildCmdResetClicked);
			this.bn_OpenTargetFolder.Clicked += new global::System.EventHandler (this.bn_OpenTargetFolderClick);
			this.bn_Run.Clicked += new global::System.EventHandler (this.bn_RunClick);
			this.bn_Stop.Clicked += new global::System.EventHandler (this.OnBnStopClicked);
			this.bn_Close.Clicked += new global::System.EventHandler (this.OnBnCloseClicked);
		}
	}
}
