
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.D.OptionPanels
{
	public partial class DCompilerOptions
	{
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.Table table6;
		
		private global::Gtk.Button btnDefaults;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Entry txtBinPath;
		
		private global::Gtk.Button button_BinPathBrowser;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.ComboBox cmbCompilers;
		
		private global::Gtk.ToggleButton btnMakeDefault;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Button btnDebugArguments;
		
		private global::Gtk.Button btnReleaseArguments;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label28;
		
		private global::Gtk.Label label29;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label30;
		
		private global::Gtk.Label label31;
		
		private global::Gtk.Entry txtCompiler;
		
		private global::Gtk.Entry txtConsoleAppLinker;
		
		private global::Gtk.Entry txtSharedLibLinker;
		
		private global::Gtk.Entry txtStaticLibLinker;
		
		private global::Gtk.Notebook notebook2;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView text_DefaultLibraries;
		
		private global::Gtk.CheckButton check_enableLibPrefixing;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TextView text_Includes;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.Button button_AddInclude;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.TextView tb_ArgPatterns;
		
		private global::Gtk.Label label4;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.D.OptionPanels.DCompilerOptions
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.D.OptionPanels.DCompilerOptions";
			// Container child MonoDevelop.D.OptionPanels.DCompilerOptions.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.table6 = new global::Gtk.Table (((uint)(7)), ((uint)(2)), false);
			this.table6.Name = "table6";
			this.table6.RowSpacing = ((uint)(6));
			this.table6.ColumnSpacing = ((uint)(6));
			// Container child table6.Gtk.Table+TableChild
			this.btnDefaults = new global::Gtk.Button ();
			this.btnDefaults.CanFocus = true;
			this.btnDefaults.Name = "btnDefaults";
			this.btnDefaults.UseUnderline = true;
			this.btnDefaults.Label = global::MonoDevelop.Core.GettextCatalog.GetString ("Defaults");
			this.table6.Add (this.btnDefaults);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table6 [this.btnDefaults]));
			w1.TopAttach = ((uint)(6));
			w1.BottomAttach = ((uint)(7));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 2;
			// Container child hbox2.Gtk.Box+BoxChild
			this.txtBinPath = new global::Gtk.Entry ();
			this.txtBinPath.CanFocus = true;
			this.txtBinPath.Name = "txtBinPath";
			this.txtBinPath.IsEditable = true;
			this.txtBinPath.InvisibleChar = '●';
			this.hbox2.Add (this.txtBinPath);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtBinPath]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button_BinPathBrowser = new global::Gtk.Button ();
			this.button_BinPathBrowser.CanFocus = true;
			this.button_BinPathBrowser.Name = "button_BinPathBrowser";
			this.button_BinPathBrowser.UseUnderline = true;
			this.button_BinPathBrowser.Label = global::MonoDevelop.Core.GettextCatalog.GetString ("Browse...");
			this.hbox2.Add (this.button_BinPathBrowser);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button_BinPathBrowser]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.table6.Add (this.hbox2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table6 [this.hbox2]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 2;
			// Container child hbox4.Gtk.Box+BoxChild
			this.cmbCompilers = global::Gtk.ComboBox.NewText ();
			this.cmbCompilers.Name = "cmbCompilers";
			this.hbox4.Add (this.cmbCompilers);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.cmbCompilers]));
			w5.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnMakeDefault = new global::Gtk.ToggleButton ();
			global::Gtk.Tooltips w6 = new Gtk.Tooltips ();
			w6.SetTip (this.btnMakeDefault, "Click to make the current configuration default", "Click to make the current configuration default");
			this.btnMakeDefault.Name = "btnMakeDefault";
			this.btnMakeDefault.UseUnderline = true;
			this.btnMakeDefault.Active = true;
			this.btnMakeDefault.Label = global::MonoDevelop.Core.GettextCatalog.GetString ("Make Default");
			this.hbox4.Add (this.btnMakeDefault);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnMakeDefault]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.table6.Add (this.hbox4);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table6 [this.hbox4]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.btnDebugArguments = new global::Gtk.Button ();
			this.btnDebugArguments.CanFocus = true;
			this.btnDebugArguments.Name = "btnDebugArguments";
			this.btnDebugArguments.UseUnderline = true;
			this.btnDebugArguments.Label = global::MonoDevelop.Core.GettextCatalog.GetString ("Debug Arguments");
			this.hbox8.Add (this.btnDebugArguments);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.btnDebugArguments]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.btnReleaseArguments = new global::Gtk.Button ();
			this.btnReleaseArguments.CanFocus = true;
			this.btnReleaseArguments.Name = "btnReleaseArguments";
			this.btnReleaseArguments.UseUnderline = true;
			this.btnReleaseArguments.Label = global::MonoDevelop.Core.GettextCatalog.GetString ("Release Arguments");
			this.hbox8.Add (this.btnReleaseArguments);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.btnReleaseArguments]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.table6.Add (this.hbox8);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table6 [this.hbox8]));
			w11.TopAttach = ((uint)(6));
			w11.BottomAttach = ((uint)(7));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::MonoDevelop.Core.GettextCatalog.GetString ("Toolchain bin path");
			this.table6.Add (this.label2);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table6 [this.label2]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label28 = new global::Gtk.Label ();
			this.label28.Name = "label28";
			this.label28.LabelProp = global::MonoDevelop.Core.GettextCatalog.GetString ("\"Static library\" linker");
			this.table6.Add (this.label28);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table6 [this.label28]));
			w13.TopAttach = ((uint)(5));
			w13.BottomAttach = ((uint)(6));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label29 = new global::Gtk.Label ();
			this.label29.Name = "label29";
			this.label29.LabelProp = global::MonoDevelop.Core.GettextCatalog.GetString ("\"Shared library\" linker");
			this.table6.Add (this.label29);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table6 [this.label29]));
			w14.TopAttach = ((uint)(4));
			w14.BottomAttach = ((uint)(5));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::MonoDevelop.Core.GettextCatalog.GetString ("Compiler");
			this.table6.Add (this.label3);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table6 [this.label3]));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label30 = new global::Gtk.Label ();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::MonoDevelop.Core.GettextCatalog.GetString ("\"Executable\" linker");
			this.table6.Add (this.label30);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table6 [this.label30]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label31 = new global::Gtk.Label ();
			this.label31.Name = "label31";
			this.label31.LabelProp = global::MonoDevelop.Core.GettextCatalog.GetString ("Compiler executable");
			this.table6.Add (this.label31);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table6 [this.label31]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.txtCompiler = new global::Gtk.Entry ();
			this.txtCompiler.CanFocus = true;
			this.txtCompiler.Name = "txtCompiler";
			this.txtCompiler.IsEditable = true;
			this.txtCompiler.InvisibleChar = '•';
			this.table6.Add (this.txtCompiler);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table6 [this.txtCompiler]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.txtConsoleAppLinker = new global::Gtk.Entry ();
			this.txtConsoleAppLinker.CanFocus = true;
			this.txtConsoleAppLinker.Name = "txtConsoleAppLinker";
			this.txtConsoleAppLinker.IsEditable = true;
			this.txtConsoleAppLinker.InvisibleChar = '•';
			this.table6.Add (this.txtConsoleAppLinker);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table6 [this.txtConsoleAppLinker]));
			w19.TopAttach = ((uint)(3));
			w19.BottomAttach = ((uint)(4));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.txtSharedLibLinker = new global::Gtk.Entry ();
			this.txtSharedLibLinker.CanFocus = true;
			this.txtSharedLibLinker.Name = "txtSharedLibLinker";
			this.txtSharedLibLinker.IsEditable = true;
			this.txtSharedLibLinker.InvisibleChar = '•';
			this.table6.Add (this.txtSharedLibLinker);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table6 [this.txtSharedLibLinker]));
			w20.TopAttach = ((uint)(4));
			w20.BottomAttach = ((uint)(5));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.txtStaticLibLinker = new global::Gtk.Entry ();
			this.txtStaticLibLinker.CanFocus = true;
			this.txtStaticLibLinker.Name = "txtStaticLibLinker";
			this.txtStaticLibLinker.IsEditable = true;
			this.txtStaticLibLinker.InvisibleChar = '•';
			this.table6.Add (this.txtStaticLibLinker);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table6 [this.txtStaticLibLinker]));
			w21.TopAttach = ((uint)(5));
			w21.BottomAttach = ((uint)(6));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox8.Add (this.table6);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.table6]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 1;
			this.notebook2.ShowBorder = false;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.text_DefaultLibraries = new global::Gtk.TextView ();
			w6.SetTip (this.text_DefaultLibraries, "A line-separated list of library references to link in by default", "A line-separated list of library references to link in by default");
			this.text_DefaultLibraries.HeightRequest = 80;
			this.text_DefaultLibraries.CanFocus = true;
			this.text_DefaultLibraries.Name = "text_DefaultLibraries";
			this.GtkScrolledWindow.Add (this.text_DefaultLibraries);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w24.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.check_enableLibPrefixing = new global::Gtk.CheckButton ();
			w6.SetTip (this.check_enableLibPrefixing, "If checked, all referenced libraries that can not be found locally will be stripped by their file extensions and get a \"-L-l\" prefix as they are passed to the compiler during project building.\n'../myCustomLib/bin/myCustomLib.a' remains untouched.\n'libphobos2.a' becomes '-L-llibphobos2' on compilation.\nThis is mainly activated when using the gdc compiler.", "If checked, all referenced libraries that can not be found locally will be stripped by their file extensions and get a \"-L-l\" prefix as they are passed to the compiler during project building.\n'../myCustomLib/bin/myCustomLib.a' remains untouched.\n'libphobos2.a' becomes '-L-llibphobos2' on compilation.\nThis is mainly activated when using the gdc compiler.");
			this.check_enableLibPrefixing.CanFocus = true;
			this.check_enableLibPrefixing.Name = "check_enableLibPrefixing";
			this.check_enableLibPrefixing.Label = global::MonoDevelop.Core.GettextCatalog.GetString ("Enable gdc-specific import lib prefix stripping (e.g. libopengl32.a -> opengl32)");
			this.check_enableLibPrefixing.Active = true;
			this.check_enableLibPrefixing.DrawIndicator = true;
			this.check_enableLibPrefixing.UseUnderline = true;
			this.vbox2.Add (this.check_enableLibPrefixing);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.check_enableLibPrefixing]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.notebook2.Add (this.vbox2);
			// Notebook tab
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::MonoDevelop.Core.GettextCatalog.GetString ("Default Libraries");
			this.notebook2.SetTabLabel (this.vbox2, this.label12);
			this.label12.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.table2 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			w6.SetTip (this.GtkScrolledWindow1, "Line-separated list of paths where the compiler (and the code completion engine!) shall look in to resolve imports.", "Line-separated list of paths where the compiler (and the code completion engine!) shall look in to resolve imports.");
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.text_Includes = new global::Gtk.TextView ();
			this.text_Includes.CanFocus = true;
			this.text_Includes.Name = "text_Includes";
			this.GtkScrolledWindow1.Add (this.text_Includes);
			this.table2.Add (this.GtkScrolledWindow1);
			// Container child table2.Gtk.Table+TableChild
			this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.button_AddInclude = new global::Gtk.Button ();
			this.button_AddInclude.CanFocus = true;
			this.button_AddInclude.Name = "button_AddInclude";
			this.button_AddInclude.UseUnderline = true;
			this.button_AddInclude.Label = global::MonoDevelop.Core.GettextCatalog.GetString ("Browse & Add");
			this.table3.Add (this.button_AddInclude);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table3 [this.button_AddInclude]));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table2.Add (this.table3);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table2 [this.table3]));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook2.Add (this.table2);
			global::Gtk.Notebook.NotebookChild w31 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.table2]));
			w31.Position = 1;
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::MonoDevelop.Core.GettextCatalog.GetString ("Includes");
			this.notebook2.SetTabLabel (this.table2, this.label1);
			this.label1.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.tb_ArgPatterns = new global::Gtk.TextView ();
			this.tb_ArgPatterns.CanFocus = true;
			this.tb_ArgPatterns.Name = "tb_ArgPatterns";
			this.GtkScrolledWindow2.Add (this.tb_ArgPatterns);
			this.notebook2.Add (this.GtkScrolledWindow2);
			global::Gtk.Notebook.NotebookChild w33 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.GtkScrolledWindow2]));
			w33.Position = 2;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::MonoDevelop.Core.GettextCatalog.GetString ("[Arg Patterns]");
			this.notebook2.SetTabLabel (this.GtkScrolledWindow2, this.label4);
			this.label4.ShowAll ();
			this.vbox8.Add (this.notebook2);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.notebook2]));
			w34.Position = 1;
			this.Add (this.vbox8);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.btnDebugArguments.Clicked += new global::System.EventHandler (this.btnDebugArguments_Clicked);
			this.btnReleaseArguments.Clicked += new global::System.EventHandler (this.btnReleaseArguments_Clicked);
			this.cmbCompilers.Changed += new global::System.EventHandler (this.OnCmbCompilersChanged);
			this.btnMakeDefault.Released += new global::System.EventHandler (this.OnTogglebuttonMakeDefaultPressed);
			this.button_BinPathBrowser.Clicked += new global::System.EventHandler (this.OnButtonBinPathBrowserClicked);
			this.btnDefaults.Clicked += new global::System.EventHandler (this.OnBtnDefaultsClicked);
			this.button_AddInclude.Clicked += new global::System.EventHandler (this.OnButtonAddIncludeClicked);
		}
	}
}
