
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.D
{
	public partial class FormattingPanelWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.D.FormattingPanelWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.D.FormattingPanelWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
