
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.D
{
	public partial class ExpressionEvaluationWidget
	{
		private global::Gtk.VPaned vpaned1;
		private global::Mono.TextEditor.TextEditor inputEditor;
		private global::Mono.TextEditor.TextEditor editor;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.D.ExpressionEvaluationWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.D.ExpressionEvaluationWidget";
			// Container child MonoDevelop.D.ExpressionEvaluationWidget.Gtk.Container+ContainerChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 77;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.inputEditor = new global::Mono.TextEditor.TextEditor ();
			this.inputEditor.Events = ((global::Gdk.EventMask)(2346756));
			this.inputEditor.Name = "inputEditor";
			this.inputEditor.TabsToSpaces = false;
			this.inputEditor.SelectionAnchor = 0;
			this.inputEditor.HighlightSearchPattern = false;
			this.inputEditor.IsCaseSensitive = false;
			this.inputEditor.IsWholeWordOnly = false;
			this.vpaned1.Add (this.inputEditor);
			global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.inputEditor]));
			w1.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.editor = new global::Mono.TextEditor.TextEditor ();
			this.editor.Events = ((global::Gdk.EventMask)(2346756));
			this.editor.Name = "editor";
			this.editor.TabsToSpaces = false;
			this.editor.SelectionAnchor = 0;
			this.editor.HighlightSearchPattern = false;
			this.editor.IsCaseSensitive = false;
			this.editor.IsWholeWordOnly = false;
			this.vpaned1.Add (this.editor);
			this.Add (this.vpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
